# conda env create --file environment.yml
name: 'llm'
channels:
  - conda-forge
dependencies:
  - python = 3.12
  - pip
  
  ## uncomment for use with Jupyter
  - ipykernel

  # Conda packages
  - pandas
  - matplotlib
  - plotly
  
  ## PyPI packages
  - pip: 
    - python-dotenv
    - langchain
    - langchain-community 
    - langchain-core
    - langchain-openai 
    - langchainhub 
    - openai
    - anthropic
    - python-dotenv
    - chromadb
    - scipy=1.12
    - scikit-learn
    - gensim
    - plotly
    - nbformat
    - matplotlib
    - ipywidgets
    - transformers[torch]
    - accelerate
    - sentence-transformers


